#!/bin/bash

pacmd load-module module-remap-sink sink_name=combined-mono master=alsa_output.usb-GN_Audio_A_S_Jabra_EVOLVE_30_II_0002ED9FCD2E07-00.analog-stereo channels=4 master_channel_map=front-right,front-left,front-right,front-left channel_map=front-left,front-left,front-right,front-right

exit 0

